plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id("com.gradleup.shadow") version "9.4.1"
}

version = project.mod_version
group = project.maven_group

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"dlaw-fabric" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

}

configurations {
	// Custom resolvable configuration to include only JDA and its deps
	shadedImplementation {
		canBeResolved = true
		canBeConsumed = false
	}

	// Tell gradle that everything marked shadedImplementation should
	// be available in IDE too.
	implementation.extendsFrom(shadedImplementation)
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	shadedImplementation("net.dv8tion:JDA:$project.jda_version")
	shadedImplementation("com.sparkjava:spark-core:2.9.4")
	// https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-xml
	shadedImplementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.20.1")
	implementation('me.lucko:fabric-permissions-api:0.7.0')

	compileOnly("org.projectlombok:lombok:1.18.46")
	annotationProcessor("org.projectlombok:lombok:1.18.46")

	testCompileOnly("org.projectlombok:lombok:1.18.46")
	testAnnotationProcessor("org.projectlombok:lombok:1.18.46")
}

shadowJar {
	configurations = [project.configurations.shadedImplementation]
	archiveClassifier.set("") // temporary classifier before remap

	// Relocate the entire kotlinx.datetime package
	relocate 'kotlinx.datetime', 'com.lukeonuke.dlawfabric.libs.kotlinx.datetime'

	// 3. (Optional but Recommended) Exclude Kotlin metadata
	// This prevents "module-info" or metadata conflicts with other mods
	exclude 'META-INF/kotlin-datetime.kotlin_module'
	exclude 'META-INF/versions/**'

	mergeServiceFiles()
}


processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
